### ISSUE TITLE
permission denied and all nginx.conf files deleted on dokku ps:rebuild

### ISSUE THREAD

**Issue by paulusm** [gliderlabs/sigil#115]
Running Dokku v0.34.4 on Ubuntu 22.04

When I did a rebuild this morning the end of the build process halted at:

`/usr/bin/sigil - Permission denied' and the rebuild failed.

Might be something I did, but the failure also seemed to delete ALL the nginx confs from every deployed app in /home/dokku

Rolling back to gliderlabs-sigil 0.10.1 fixed this.

`sudo apt install gliderlabs-sigil=0.10.1`

**Comment by josegonzalez** [comment]
Seems like the release didn't work as expected... I'm away from a keyboard till late today but will try and pull packages in the meantime.

**Comment by josegonzalez** [comment]
We need some option [here](https://github.com/gliderlabs/sigil/blob/main/.github/workflows/tagged-release.yml#L39-L52) to build the binary from the cmd folder instead of root. I haven't looked into that yet.

**Comment by josegonzalez** [comment]
Okay this should be fixed. Needed to set the build [pkg here](https://github.com/gliderlabs/sigil/pull/129/files#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721R62).
