### ISSUE TITLE
error parsing solr-config.xml

### ISSUE THREAD

**Issue by gilesw** [gliderlabs/sigil#25]
Hi Gliderlabs,

I was really excited about this project because it seemed to exactly fit the bill for what I needed. However I found one config file that we template that it failed on:-

https://gist.github.com/gilesw/6d8e6e00ded8575dfd0880e43193209a

cat tests/solrconfig.xml | ./sigil -p

unexpected op: %!s(int32=46)

So the problem seems to be this syntax:-

${var:test}

So the solrconfig files doesn't follow the POSIX standards?

class="${solr.directoryFactory:solr.NRTCachingDirectoryFactory}"/>

**Comment by gilesw** [comment]
Okay I've identified the problem line as:-

  <lib dir="${solr.install.dir:../../../..}/contrib/extraction/lib" regex=".*\.jar" />

**Comment by progrium** [comment]
Correct that is not valid POSIX: http://pubs.opengroup.org/onlinepubs/007904875/utilities/xcu_chap02.html#tag_02_06_02

**Comment by gilesw** [comment]
@progrium what's your opinion on how best to support this. We currently use envsubst which does parse the file without error but doesn't replace these specific "Java property substitutions." They are parsed on solr startup.

**Comment by progrium** [comment]
I don't really know the problem well enough to have an opinion.

**Comment by josegonzalez** [comment]
If you need replacements, you can use our existing forms for performing replacements. To ignore things, you could also print them out: `{{ '$' }}`.

I don't think we should add support for non-standard posix variables, and though the workarounds don't feel appealing, I think this is an okay decision to make for the project.
