### ISSUE TITLE
Feature request column lining

### ISSUE THREAD

**Issue by gilesw** [gliderlabs/sigil#27]
@progrium I'm trying to replicate a Ruby script that a workmate wrote which made for readable config files. He indented the separator and value based on the size of the longest variable.

    aaa_really_long_var = test
    var                 = test 

fyi this is the Ruby
```
size = 0
conf.keys.map { |k|
  size = k.length if format and k.length > size
  k
}.select { |k|
  scope.function_sem(['is_scalar',conf[k]]) and k =~ /^[a-zA-Z]/
}.sort.each { |k|
  if quote != ''
    conf[k] = "#{quote}#{conf[k].to_s.gsub(Regexp.new("(#{quote})"),'\\\\\1')}#{quote}"
  end
-%>
<%= sprintf("%-#{size}s",(k_upcase ? k.upcase : k)) %><%= separator %><%= conf[k] %>
<%- } -%>
```

**Comment by progrium** [comment]
Main part of that script that does what you're talking about is `sprintf("%-#{size}s" ...)`.

The equivalent would be using the builtin `printf`:
```
$ echo '{{printf "%-10s" "foo"}} = bar' | sigil
foo        = bar
```
