### ISSUE TITLE
Release 0.4.x or 0.5

### ISSUE THREAD

**Issue by IlyaSemenov** [gliderlabs/sigil#45]
I see the latest master has had `substr` function for 2 years by now but it's not in the latest published 0.4 release (and can't be used in Dokku's `nginx.config.sigil` for that reason). Even though the development seems to have stalled, maybe you can just publish a new release with the latest updates?

**Comment by josegonzalez** [comment]
I missed this and will take care of it Real Soon™

**Comment by josegonzalez** [comment]
Real Soon™ is nowish. Our CircleCI setup is broken, so I'm working on that now...

**Comment by josegonzalez** [comment]
CircleCI is fixed!

**Comment by josegonzalez** [comment]
0.5.0 was released and the build pipeline has been setup to create packages as well.
