### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by andye2004** [gliderlabs/sigil#47]
Just a question, I'm interested in using sigil but in tests have found that the release version don't support go template features such as:-

```
{{- if condition }} ... {{ end }} 
```

Do you have any plans to release a newer version with more up to date go template features included?

**Comment by josegonzalez** [comment]
Soon? Working on this now as I need it for Dokku...

**Comment by josegonzalez** [comment]
0.5.0 was released and the build pipeline has been setup to create packages as well.
