### ISSUE TITLE
Interpolation of include vars

### ISSUE THREAD

**Issue by Alars-ALIT** [gliderlabs/sigil#9]
Hi guys, 

I would like to expand variables sent to for example an include, such as:

{{ include "consul.yaml.sigil" "id=bootstrap" "az=$AZ" }}

..is this possible in some way?

Thanks,
/Andreas

**Comment by progrium** [comment]
Yeah, that's actually how it works already. No docs yet.

**Comment by Alars-ALIT** [comment]
Ohh, but: 
 > echo '{{ include "test.txt" "test=$outer"}}' | sigil outer=glider
..gives output:
> $outer 
(when test.txt contains {{ $test }})
What am i doing wrong?

**Comment by progrium** [comment]
Oh I see, you're right it doesn't interpolate so you'd have to do:
`echo '{{ include "test.txt" (printf "test=%s" $outer) }}' | sigil outer=glider`
Though alternatively you could pass all vars in:
`echo '{{ include "test.txt" . }}' | sigil test=glider`
But I agree it would be nice to have variables interpolated in include var definitions.

**Comment by Alars-ALIT** [comment]
Passing all the vars in is exactly what I wanted. Thanks alot!

**Comment by srigi** [comment]
How can I extend the above example (`printf`) for more variables passed to the included template?

**Comment by josegonzalez** [comment]
Interpolated variables seems messy since we'd probably need to do some sort of weird, 2-phase processing of incoming templates, as it could be possible that someone defines a variable within the golang template and passes it into the `include`.

I think as such, the `printf` format is the way to go.
